const bodyElement = document.getElementsByTagName('body')[0];
const messageDiv = document.createElement('div');
messageDiv.style.position = "fixed";
messageDiv.id = "ws-toast";
messageDiv.style.left = "0";
messageDiv.style.top = "0";
messageDiv.style.width = "100%";
messageDiv.style.height = "30px";
messageDiv.style.background = "rgba(0, 174, 157, .9)";
messageDiv.style.color = "black";
messageDiv.style.zIndex = "10005";
messageDiv.style.textAlign = "center";
messageDiv.style.fontSize = "18px";
messageDiv.style.padding = "2px";
messageDiv.innerHTML="선택할 영역 위에서 우클릭하면 영역을 선택할 수 있습니다.";
bodyElement.appendChild(messageDiv);